### ISSUE TITLE
InfluxDB dashboard

### ISSUE THREAD

**Issue by mortenhaahr** [INTO-CPS-Association/example_digital-twin_incubator#36]
Hi,

It would be great to have some info on how to import the InfluxDB dashboards.
I think they are found under digital_twin/data_access/influxdbserver/dashboards

Thanks!

**Comment by mortenhaahr** [comment]
I just saw that I made a mistake during our meeting @clagms 
The dashboards are automatically imported to InfluxDB but I was looking at the wrong place.
Perhaps this issue is irrelevant then.

**Comment by clagms** [comment]
@mortenhaahr the fact that the documentation currently has let you astray, means something should be improved.
However, I have a bit of difficulty at the moment finding where in the documentation we could state a few words regarding the dashboards being available by default.
If you can find that, then please suggest an improvement. Otherwise please close this issue. Thank you!

**Comment by clagms** [comment]
@mortenhaahr should we close this? Thanks!
